-- MySQL Script generated by MySQL Workbench
-- 08/25/15 15:59:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema scout_camp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scout_camp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scout_camp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `scout_camp` ;

-- -----------------------------------------------------
-- Table `scout_camp`.`crest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout_camp`.`crest` (
  `crest_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `crest_name` VARCHAR(45) NOT NULL COMMENT '',
  `crest_image` VARCHAR(45) NOT NULL COMMENT '',
  `crest_title` VARCHAR(45) NULL COMMENT '',
  `crest_desc` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`crest_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scout_camp`.`tier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout_camp`.`tier` (
  `tier_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tier_name` VARCHAR(45) NOT NULL COMMENT '',
  `tier_image` VARCHAR(45) NOT NULL COMMENT '',
  `tier_tile` VARCHAR(45) NULL COMMENT '',
  `tier_desc` VARCHAR(45) NULL COMMENT '',
  `tier_level` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`tier_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scout_camp`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout_camp`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `facebook_id` VARCHAR(45) NULL COMMENT '',
  `user_name` VARCHAR(45) NOT NULL COMMENT '',
  `crest_crest_id` INT NOT NULL COMMENT '',
  `tier_tier_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`user_id`, `crest_crest_id`, `tier_tier_id`)  COMMENT '',
  UNIQUE INDEX `id_facebook_UNIQUE` (`facebook_id` ASC)  COMMENT '',
  UNIQUE INDEX `id_user_UNIQUE` (`user_id` ASC)  COMMENT '',
  INDEX `fk_user_crest_idx` (`crest_crest_id` ASC)  COMMENT '',
  INDEX `fk_user_tier1_idx` (`tier_tier_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_crest`
    FOREIGN KEY (`crest_crest_id`)
    REFERENCES `scout_camp`.`crest` (`crest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_tier1`
    FOREIGN KEY (`tier_tier_id`)
    REFERENCES `scout_camp`.`tier` (`tier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scout_camp`.`badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout_camp`.`badge` (
  `badge_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `badge_name` VARCHAR(45) NOT NULL COMMENT '',
  `badge_image` VARCHAR(45) NOT NULL COMMENT '',
  `badge_title` VARCHAR(45) NULL COMMENT '',
  `badge_desc` VARCHAR(45) NULL COMMENT '',
  `badge_point` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`badge_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `scout_camp`.`user_tem_badge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scout_camp`.`user_tem_badge` (
  `user_user_id` INT NOT NULL COMMENT '',
  `user_crest_crest_id` INT NOT NULL COMMENT '',
  `user_tier_tier_id` INT NOT NULL COMMENT '',
  `badge_badge_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`user_user_id`, `user_crest_crest_id`, `user_tier_tier_id`, `badge_badge_id`)  COMMENT '',
  INDEX `fk_user_has_badge_badge1_idx` (`badge_badge_id` ASC)  COMMENT '',
  INDEX `fk_user_has_badge_user1_idx` (`user_user_id` ASC, `user_crest_crest_id` ASC, `user_tier_tier_id` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_badge_user1`
    FOREIGN KEY (`user_user_id` , `user_crest_crest_id` , `user_tier_tier_id`)
    REFERENCES `scout_camp`.`user` (`user_id` , `crest_crest_id` , `tier_tier_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_badge_badge1`
    FOREIGN KEY (`badge_badge_id`)
    REFERENCES `scout_camp`.`badge` (`badge_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
